#%RAML 1.0 NamedExample
displayName: postThing
value: {
   "value":[
      {
         "name":"Things",
         "url":"http://sensorThings.himotion.it/v1.0/Things"
      },
      {
         "name":"Locations",
         "url":"http://sensorThings.himotion.it/v1.0/Locations"
      },
      {
         "name":"HistoricalLocations",
         "url":"http://sensorThings.himotion.it/v1.0/HistoricalLocations"
      },
      {
         "name":"Datastreams",
         "url":"http://sensorThings.himotion.it/v1.0/Datastreams"
      },
      {
         "name":"Sensors",
         "url":"http://sensorThings.himotion.it/v1.0/Sensors"
      },
      {
         "name":"Observations",
         "url":"http://sensorThings.himotion.it/v1.0/Observations"
      },
      {
         "name":"ObservedProperties",
         "url":"http://sensorThings.himotion.it/v1.0/ObservedProperties"
      },
      {
         "name":"FeaturesOfInterest",
         "url":"http://sensorThings.himotion.it/v1.0/FeaturesOfInterest"
      }
   ]
  }