#%RAML 1.0 Trait
queryParameters: 
  $expand:
    type: string
    required: false
    
description: returns the entity set of Things as well as each of the Datastreams associated with each Thing entity.
