#%RAML 1.0 Trait
queryParameters: 
  $filter:
    type: string
    required: false
    
description: Use $filter query option to perform conditional operations on the property values and filter request result.
