#%RAML 1.0 Trait
queryParameters: 
  $orderby:
    type: string
    required: false
description: Use $orderby query option to sort the response based on properties of requested entity in accending (asc) or decending (desc) order
