#%RAML 1.0 Trait
queryParameters: 
  $select:
    type: string
    required: false
description: The $select query option requests specific properties of an entity from the SensorThings service. This query option is used to help reduce the amount of information returned from the server.