#%RAML 1.0 Trait
queryParameters: 
  $skip:
    type: integer
    required: false
    
description: Use $skip to specify the numer of entities that should be skipped before returning the requested entities.

